//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormVision.Resources.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormVision.Resources.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataPage_PageTitle {
            get {
                return ResourceManager.GetString("DataPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string HomePage_ActionsContainer_DataButtonText {
            get {
                return ResourceManager.GetString("HomePage_ActionsContainer_DataButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HomePage_ActionsContainer_SettingsButtonText {
            get {
                return ResourceManager.GetString("HomePage_ActionsContainer_SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string HomePage_ActionsContainer_TasksButtonText {
            get {
                return ResourceManager.GetString("HomePage_ActionsContainer_TasksButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed tasks.
        /// </summary>
        public static string HomePage_EventsContainer_CompletedTasksCaptionLabelText {
            get {
                return ResourceManager.GetString("HomePage_EventsContainer_CompletedTasksCaptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionStatus.
        /// </summary>
        public static string HomePage_EventsContainer_ConnectionStatusCaptionLabelText {
            get {
                return ResourceManager.GetString("HomePage_EventsContainer_ConnectionStatusCaptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued tasks.
        /// </summary>
        public static string HomePage_EventsContainer_IssuedTasksCaptionLabelText {
            get {
                return ResourceManager.GetString("HomePage_EventsContainer_IssuedTasksCaptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks queue (all/your).
        /// </summary>
        public static string HomePage_EventsContainer_TasksQueueCaptionLabelText {
            get {
                return ResourceManager.GetString("HomePage_EventsContainer_TasksQueueCaptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload status.
        /// </summary>
        public static string HomePage_EventsContainer_UploadStatusCaptionLabelText {
            get {
                return ResourceManager.GetString("HomePage_EventsContainer_UploadStatusCaptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string HomePage_PageTitle {
            get {
                return ResourceManager.GetString("HomePage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfilePage_PageTitle {
            get {
                return ResourceManager.GetString("ProfilePage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPage_PageTitle {
            get {
                return ResourceManager.GetString("SettingsPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TasksPage_PageTitle {
            get {
                return ResourceManager.GetString("TasksPage_PageTitle", resourceCulture);
            }
        }
    }
}
